default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-toml
      - id: pretty-format-json
        exclude: '(^.vscode/)'
      - id: check-yaml
        exclude: "^mkdocs.yml"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args:
          - --fix

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        args: [requirements/requirements.in]
        files: ^(requirements/requirements.in|pyproject.toml)$
      - id: pip-compile
        name: pip-compile requirements-docs.in
        args: [requirements/requirements-docs.in]
        files: ^(requirements/requirements-docs.in|pyproject.toml)$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements/requirements-dev.in]
        files: ^(requirements/requirements-dev.in|pyproject.toml)$
      - id: pip-compile
        name: pip-compile requirements-test.in
        args: [requirements/requirements-test.in]
        files: ^(requirements/requirements-test.in|pyproject.toml)$

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
